language: python
python:
  - '2.7'
install:
  - pip install ansible ansible-lint
  - packer --version
  - terraform --version
script:
  - ls -l
  - cd packer
  - packer validate app_image.json
  - packer validate db_image.json
  - cd ../terraform/stage
  - terraform init
  - terraform validate
  - cd ../prod
  - terraform init
  - terraform validate
  - cd ../..
  - ansible-lint ansible/playbooks || true
