language: python
python:
  - '2.7'
install:
  - pip install ansible ansible-lint
script:
  - cd packer
  - packer validate packer/app_image.json
  - packer validate packer/db_image.json
  - cd ../terraform/stage
  - terraform init
  - terraform validate
  - cd ../prod
  - terraform init
  - terraform validate
  - cd ../..
  - ansible-lint ansible/playbooks || true
