language: python
python:
  - '2.7'
before_install:
  - packer --version || wget https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip
  - terraform --version || wget https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip
  - if ls *.zip 2>/dev/null; then mkdir bin && unzip *.zip -d bin && export PATH=$PATH:$PWD/bin; fi
install:
  - packer --version
  - terraform --version
  - pip install ansible ansible-lint
script:
  - ls -l
  - cd packer
  - packer validate app_image.json
  - packer validate db_image.json
  - cd ../terraform/stage
  - terraform init
  - terraform validate
  - cd ../prod
  - terraform init
  - terraform validate
  - cd ../..
  - ansible-lint ansible/playbooks || true
