language: python
python:
  - '2.7'
install:
  - wget https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip
  - unzip terraform_0.11.4_linux_amd64.zip
  - wget https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip
  - unzip packer_1.2.1_linux_amd64.zip
  - chmod 755 packer terraform
  - pip install ansible ansible-lint
script:
  - cd packer
  - ../packer validate packer/app_image.json
  - ../packer validate packer/db_image.json
  - cd ../terraform/stage
  - ../../terraform init
  - ../../terraform validate
  - cd ../prod
  - ../../terraform init
  - ../../terraform validate
  - cd ../..
  - ansible-lint ansible/playbooks || true
