---
  - name: Configure app
    hosts: app
    become: true

    vars:
      db_host: "{{ hostvars.dbserver.gcp_data.networkInterfaces[0].networkIP | mandatory }}"

    roles:
      - app
      - { role: jdauphant.nginx }
...
