---
  - name: Configure app
    hosts: app
    become: true

    vars:
      db_host: "{{ hostvars.dbserver.gcp_data.networkInterfaces[0].networkIP | mandatory }}"

    tasks:

      - include_role:
          name: app

      - include_role:
          name: jdauphant.nginx
        vars:
          nginx_sites: "{{ nginx_conf.nginx_sites }}"

      - debug:
          msg: "{{ nginx_conf }}"
...
