---
- name: db provisioning
  hosts: all
  become: true
  tasks:

  - name: apt add key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
      state: present

  - name: apt add repository
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      filename: mongodb-org-3.2.list
      state: present
      update_cache: yes

  - name: apt install mongod
    apt:
      name: mongodb-org
      state: present

  - name: start and enable service
    systemd:
      name: mongod
      state: started
      enabled: yes
...
