---
  - name: Configure app
    hosts: app
    vars:
      # db_host: 10.132.0.2
      db_host: "{{ hostvars.dbserver.gcp_data.networkInterfaces[0].networkIP | mandatory }}"
    become: true

    tasks:
      - name: add unit file for puma
        copy:
          src: files/puma.service
          dest: /etc/systemd/system/puma.service
        notify: reload puma

      - name: add env for puma
        template:
          src: templates/db_config.j2
          dest: /home/appuser/db_config
          owner: appuser
          group: appuser

      - name: enable puma service
        systemd:
          name: puma
          enabled: yes

    handlers:
      - name: reload puma
        systemd:
          name: puma
          state: restarted
...
