---
  - name: Deploy app
    hosts: app

    tasks:
      - name: checkout app
        git:
          repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
          dest: /home/appuser/reddit
          version: monolith

      - name: build app
        bundler:
          state: present
          chdir: /home/appuser/reddit
        notify: restart puma

    handlers:
      - name: restart puma
        become: true
        systemd:
          name: puma
          state: restarted
...
