---
  - name: Configure db
    hosts: db
    become: true
    tags: db-tag
    vars:
      mongo_bind_ip: 0.0.0.0

    tasks:
      - name: change mongod config file
        template:
          src: templates/mongod.conf.j2
          dest: /etc/mongod.conf
          mode: 0644
        notify: restart mongod

    handlers:
      - name: restart mongod
        service:
          name: mongod
          state: restarted

  - name: Configure app
    hosts: app
    vars:
      db_host: 10.132.0.2
    become: true
    tags: app-tag

    tasks:
      - name: add unit file for puma
        copy:
          src: files/puma.service
          dest: /etc/systemd/system/puma.service
        notify: reload puma

      - name: add env for puma
        template:
          src: templates/db_config.j2
          dest: /home/appuser/db_config
          owner: appuser
          group: appuser

      - name: enable puma service
        systemd:
          name: puma
          enabled: yes

    handlers:
      - name: reload puma
        systemd:
          name: puma
          state: restarted

  - name: Deploy app
    hosts: app
    tags: deploy-tag

    tasks:
      - name: checkout app
        git:
          repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
          dest: /home/appuser/reddit
          version: monolith

      - name: build app
        bundler:
          state: present
          chdir: /home/appuser/reddit
        notify: restart puma

    handlers:
      - name: restart puma
        become: true
        systemd:
          name: puma
          state: restarted
...
